type token = 
| INPUT | PRINT
| IDENTIFIER of string 
| FILENAME of string
| INT of int | FLOAT of float | BOOL of bool 
| NOT | AND | OR 
| PLUS | MINUS | TIMES | DIVIDE | ABS 
| EQ | NEQ | LT | GT | LEQ | GEQ | MOD 
| LBRACKET | RBRACKET | LBRACE | RBRACE | LPAREN | RPAREN
| COMMA | SEMICOLON 
| DOTPRODUCT | ANGLE | MAG | DIM | UNIT | CREATE | ZERO
| MULMATRIX | TRANSPOSE | DETERMINANT 
| ROWS | COLS | SIZE | MINOR | POWER 
| ASSIGN 
| IF | ELSE 
| FOR | WHILE 
| EOF
| ROWSWAP
| ROWREDUCE | RAISE 

